#
# Definitions are kept in @kba/anno-schema
#
swagger: '2.0'
basePath: '/'
info:
  title: 'Anno Server API'
  version: '0.0.1'
consumes:
  - application/ld+json
produces:
  - application/ld+json
tags:
  - name: anno
    description: Handling annotations
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    description: "Format: 'Bearer HIER_DAS_TOKEN'"
    in: header

##############################################################################
#
# PATHS
#
##############################################################################
paths:

  '/anno':

    head:
      tags:
        - 'anno'
      summary: 'Get all annotations that adhere to query without body'
      parameters:
        - in: 'query'
          name: 'url'
          required: true
          type: 'string'
          format: 'url'
      responses:
        200:
          description: all okay
          schema:
            $ref: '#/definitions/ListOfFullAnnotations'

    get:
      tags:
        - 'anno'
      summary: 'Get all annotations that adhere to query'
      parameters:
        - in: 'query'
          name: 'url'
          required: true
          type: 'string'
          format: 'url'
        - in: 'header'
          name: 'Prefer'
          description: '<a href="https://www.w3.org/TR/annotation-protocol/#container-representations">Preferred Container Representation</a>'
          enum:
            - 'return=representation;include="http://www.w3.org/ns/ldp#PreferMinimalContainer"'
            - 'return=representation;include="http://www.w3.org/ns/oa#PreferContainedIRIs'
            - 'return=representation;include="http://www.w3.org/ns/oa#PreferContainedDescriptions"'
      responses:
        200:
          description: all okay
          schema:
            $ref: '#/definitions/ListOfFullAnnotations'

    post:
      tags:
        - 'anno'
      security:
        - Bearer: []
      summary: 'Post a new annotation'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'New annotation to post'
          schema:
            $ref: '#/definitions/AnnotationToPost'
        - in: 'header'
          name: 'Slug'
          description: 'Preferred annotation ID'
      responses:
        200:
          description: all okay

    delete:
      tags:
        - 'anno'
      security:
        - Bearer: []
      summary: 'Wipe the store'
      parameters: []
      responses:
        200:
          description: all okay

  '/anno/{id}':

    get:
      tags: ['anno']
      summary: 'Get a single annotation including all revisions'
      parameters:
        - in: 'path'
          name: 'annoId'
          type: 'string'
          required: true
          description: 'ID of the annotation'
      responses:
        200:
          description: 'all okay'

    head:
      tags: ['anno']
      summary: 'Get a single annotation including all revisions without body'
      parameters:
        - in: 'path'
          name: 'annoId'
          type: 'string'
          required: true
          description: 'ID of the annotation'
      responses:
        200:
          description: 'all okay'

    put:
      tags: ['anno']
      summary: 'Store a new revision of an annotation'
      parameters:
        - in: 'path'
          name: 'annoId'
          type: 'string'
          required: true
          description: 'ID of the annotation'
        - in: 'body'
          name: 'body'
          description: 'Updated annotation'
          required: true
          schema:
            $ref: '#/definitions/FullAnnotation'
      responses:
        200:
          description: Created a new revision
          schema:
            $ref: '#/definitions/FullAnnotation'

    post:
      tags:
        - 'anno'
      summary: 'Add a comment'

  '/anno/{annoId}/{revId}':
    get:
      tags:
        - 'anno'
      summary: 'Get a single revision of one annotation'
      parameters:
        - in: 'path'
          name: 'annoId'
          type: 'string'
          required: true
          description: 'ID of the annotation'
        - in: 'path'
          name: 'revId'
          type: 'string'
          required: true
          description: "ID of the revision"
      responses:
        200:
          description: all okay

    head:
      tags:
        - 'anno'
      summary: 'Get a single revision of one annotation without body'
      parameters:
        - in: 'path'
          name: 'annoId'
          type: 'string'
          required: true
          description: 'ID of the annotation'
        - in: 'path'
          name: 'revId'
          type: 'string'
          required: true
          description: "ID of the revision"
      responses:
        200:
          description: all okay
